# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/huvalk/CLionProjects/TECHNOPARK/highload

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/huvalk/CLionProjects/TECHNOPARK/highload

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huvalk/CLionProjects/TECHNOPARK/highload/CMakeFiles /home/huvalk/CLionProjects/TECHNOPARK/highload/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huvalk/CLionProjects/TECHNOPARK/highload/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named highload

# Build rule for target.
highload: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 highload
.PHONY : highload

# fast build rule for target.
highload/fast:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/build
.PHONY : highload/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/main.cpp.s
.PHONY : main.cpp.s

src/Client.o: src/Client.cpp.o

.PHONY : src/Client.o

# target to build an object file
src/Client.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Client.cpp.o
.PHONY : src/Client.cpp.o

src/Client.i: src/Client.cpp.i

.PHONY : src/Client.i

# target to preprocess a source file
src/Client.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Client.cpp.i
.PHONY : src/Client.cpp.i

src/Client.s: src/Client.cpp.s

.PHONY : src/Client.s

# target to generate assembly for a file
src/Client.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Client.cpp.s
.PHONY : src/Client.cpp.s

src/Config.o: src/Config.cpp.o

.PHONY : src/Config.o

# target to build an object file
src/Config.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Config.cpp.o
.PHONY : src/Config.cpp.o

src/Config.i: src/Config.cpp.i

.PHONY : src/Config.i

# target to preprocess a source file
src/Config.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Config.cpp.i
.PHONY : src/Config.cpp.i

src/Config.s: src/Config.cpp.s

.PHONY : src/Config.s

# target to generate assembly for a file
src/Config.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Config.cpp.s
.PHONY : src/Config.cpp.s

src/ConfigParser.o: src/ConfigParser.cpp.o

.PHONY : src/ConfigParser.o

# target to build an object file
src/ConfigParser.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/ConfigParser.cpp.o
.PHONY : src/ConfigParser.cpp.o

src/ConfigParser.i: src/ConfigParser.cpp.i

.PHONY : src/ConfigParser.i

# target to preprocess a source file
src/ConfigParser.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/ConfigParser.cpp.i
.PHONY : src/ConfigParser.cpp.i

src/ConfigParser.s: src/ConfigParser.cpp.s

.PHONY : src/ConfigParser.s

# target to generate assembly for a file
src/ConfigParser.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/ConfigParser.cpp.s
.PHONY : src/ConfigParser.cpp.s

src/Request.o: src/Request.cpp.o

.PHONY : src/Request.o

# target to build an object file
src/Request.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Request.cpp.o
.PHONY : src/Request.cpp.o

src/Request.i: src/Request.cpp.i

.PHONY : src/Request.i

# target to preprocess a source file
src/Request.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Request.cpp.i
.PHONY : src/Request.cpp.i

src/Request.s: src/Request.cpp.s

.PHONY : src/Request.s

# target to generate assembly for a file
src/Request.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Request.cpp.s
.PHONY : src/Request.cpp.s

src/Response.o: src/Response.cpp.o

.PHONY : src/Response.o

# target to build an object file
src/Response.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Response.cpp.o
.PHONY : src/Response.cpp.o

src/Response.i: src/Response.cpp.i

.PHONY : src/Response.i

# target to preprocess a source file
src/Response.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Response.cpp.i
.PHONY : src/Response.cpp.i

src/Response.s: src/Response.cpp.s

.PHONY : src/Response.s

# target to generate assembly for a file
src/Response.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Response.cpp.s
.PHONY : src/Response.cpp.s

src/Server.o: src/Server.cpp.o

.PHONY : src/Server.o

# target to build an object file
src/Server.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Server.cpp.o
.PHONY : src/Server.cpp.o

src/Server.i: src/Server.cpp.i

.PHONY : src/Server.i

# target to preprocess a source file
src/Server.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Server.cpp.i
.PHONY : src/Server.cpp.i

src/Server.s: src/Server.cpp.s

.PHONY : src/Server.s

# target to generate assembly for a file
src/Server.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/Server.cpp.s
.PHONY : src/Server.cpp.s

src/ThreadRoutine.o: src/ThreadRoutine.cpp.o

.PHONY : src/ThreadRoutine.o

# target to build an object file
src/ThreadRoutine.cpp.o:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/ThreadRoutine.cpp.o
.PHONY : src/ThreadRoutine.cpp.o

src/ThreadRoutine.i: src/ThreadRoutine.cpp.i

.PHONY : src/ThreadRoutine.i

# target to preprocess a source file
src/ThreadRoutine.cpp.i:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/ThreadRoutine.cpp.i
.PHONY : src/ThreadRoutine.cpp.i

src/ThreadRoutine.s: src/ThreadRoutine.cpp.s

.PHONY : src/ThreadRoutine.s

# target to generate assembly for a file
src/ThreadRoutine.cpp.s:
	$(MAKE) -f CMakeFiles/highload.dir/build.make CMakeFiles/highload.dir/src/ThreadRoutine.cpp.s
.PHONY : src/ThreadRoutine.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... highload"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Client.o"
	@echo "... src/Client.i"
	@echo "... src/Client.s"
	@echo "... src/Config.o"
	@echo "... src/Config.i"
	@echo "... src/Config.s"
	@echo "... src/ConfigParser.o"
	@echo "... src/ConfigParser.i"
	@echo "... src/ConfigParser.s"
	@echo "... src/Request.o"
	@echo "... src/Request.i"
	@echo "... src/Request.s"
	@echo "... src/Response.o"
	@echo "... src/Response.i"
	@echo "... src/Response.s"
	@echo "... src/Server.o"
	@echo "... src/Server.i"
	@echo "... src/Server.s"
	@echo "... src/ThreadRoutine.o"
	@echo "... src/ThreadRoutine.i"
	@echo "... src/ThreadRoutine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

